# configs/model/informer.yaml
model_type: "informer"

# Model Architecture
d_model: 512
n_heads: 8
e_layers: 3
d_layers: 2
d_ff: 512
factor: 5
activation: "gelu"

# Model Specific Settings
attn: "prob"  # 'prob' or 'full'
embed: "fixed"  # 'fixed' or 'learned'
freq: "h"
distil: true
mix: true
output_attention: false

# Training
dropout: 0.1

# Optimizer
optimizer:
  name: "Adam"
  params:
    lr: 0.001
    weight_decay: 0.0001
    betas: [0.9, 0.999]
    eps: 1.0e-8

# Scheduler
scheduler:
  name: "ReduceLROnPlateau"
  params:
    mode: "min"
    factor: 0.5
    patience: 10
    min_lr: 1.0e-6
    verbose: true

# Loss
loss: "MSELoss"
loss_params: {}