# configs/model/lstm.yaml
model_type: "lstm"
hidden_size: 128
num_layers: 2
dropout: 0.1
# optimizer:
#   name: "Adam"
#   params:
#     lr: 0.001
#     weight_decay: 0.0001
#     betas: [0.9, 0.999]
#     eps: 1.0e-8
# scheduler:
#   name: "ReduceLROnPlateau"
#   params:
#     mode: "min"
#     factor: 0.5
#     patience: 10
#     min_lr: 1.0e-6
#     verbose: true
# loss: "MSELoss"
# loss_params: {}