# configs/model/timemixer.yaml
model_type: "timemixer"
d_model: 512
d_ff: 2048
n_layers: 3
top_k: 5
down_sampling_window: 2
down_sampling_layers: 2
down_sampling_method: "avg"
embed: "timeF"
freq: "h"
dropout: 0.1