# configs/hyperopt/adarnn.yaml
model_params:
  hidden_sizes: [[32, 32], [64, 64], [128, 128], [256, 256]]
  dropout: [0.1, 0.2, 0.3, 0.4]
  use_bottleneck: [true, false]
  bottleneck_width: [128, 256, 512]
  model_type: ["AdaRNN", "Boosting"]
  trans_loss: ["mmd", "coral", "cosine"]

training_params:
  batch_size: [32]
  optimizer: ['AdamW']
  learning_rate: [0.0001, 0.0005, 0.001, 0.005]
  weight_decay: [0.0001, 0.001, 0.01]