# configs/hyperopt/dlinear.yaml
model_params:
  kernel_size: [13, 25, 37, 49]  # Moving average kernel size
  individual: [false]  # false 고정이어야함

training_params:
  batch_size: [16, 32, 64, 128]
  learning_rate: [0.0001, 0.0005, 0.001, 0.005, 0.01]
  optimizer: ['Adam', 'AdamW', 'RMSprop']
  weight_decay: [0.0001, 0.0005, 0.001, 0.005]