# configs/hyperopt/tcn.yaml
model_params:
  num_channels: [[32, 64, 128], [64, 128, 256], [32, 64, 128, 256]]
  kernel_size: [2, 3, 4, 5]
  dropout: [0.1, 0.2, 0.3, 0.4, 0.5]

training_params:
  batch_size: [16, 32, 64, 128]
  learning_rate: [0.0001, 0.0005, 0.001, 0.005, 0.01]
  optimizer: ['Adam', 'AdamW', 'RMSprop']
  weight_decay: [0.0001, 0.0005, 0.001, 0.005]